### ISSUE TITLE
Issue numbers are inconsistent

### ISSUE THREAD

**Issue by jeffwidman** [mhils/backports.socketpair#2]
These two version numbers do not match: 

https://github.com/mhils/backports.socketpair/blob/b4a34fb30da003f8a878c5b40a5be2e97fab4a93/backports/socketpair/__init__.py#L1

https://github.com/mhils/backports.socketpair/blob/b4a34fb30da003f8a878c5b40a5be2e97fab4a93/setup.py#L14

To fix this long term, rather than just bumping the number, it's probably better to put version in a single place and then pull the variable into the other. This way you won't have it ever go out of sync in the future.

**Comment by mhils** [comment]
Good catch, thanks. I do this for all my new projects, turns out this one is older than expected. 😄

I just published 3.5.0.4, which fixes this. Thanks again!

**Comment by jeffwidman** [comment]
Thanks for the fast fix.
