### ISSUE TITLE
Calls exceptions that only exist in python3

### ISSUE THREAD

**Issue by jeffwidman** [mhils/backports.socketpair#4]
In https://github.com/mhils/backports.socketpair/blob/f834f594cc89481995f7e532138789996c55b47b/backports/socketpair/__init__.py#L39 it tries to catch `BlockingIOError` and `InterruptedError`. 

However, these exceptions are not part of the standard lib until `python3`. Compare https://docs.python.org/2/library/exceptions.html to https://docs.python.org/3/library/exceptions.html.

I looked into fixing it, but couldn't find obvious parallels in the python2 stdlib. There is an `io.BlockingIOError` but not positive that's the same thing... I guess we could alternatively just remove the try/catch block altogether since it effectively will never work right now...

**Comment by mhils** [comment]
Whatever works best for you. I don't maintain any python2 code anymore (lucky me), so feel free to change it as you see fit. We should maybe make sure that we don't loose 3.4 compat on the way :)

**Comment by lukebakken** [comment]
Doesn't [this section](https://github.com/mhils/backports.socketpair/blob/master/backports/socketpair/__init__.py#L36-L46) handle Python 2 / 3 compatibility correctly via the `sys.version_info` check?

**Comment by jeffwidman** [comment]
Yep, I missed that previously.
