### ISSUE TITLE
Defining (but not overwriting) `socketpair` function unconditionally?

### ISSUE THREAD

**Issue by mentalisttraceur** [mhils/backports.socketpair#6]
I was wondering: Do you think it might be useful to define the `socketpair` function **un**conditionally within this module, and only assign it to `socket.socketpair` conditionally?

So instead of:

    if not hasattr(socket, 'socketpair'):
        def socketpair(...):
            ...
        socket.socketpair = socketpair

..something like this:

    def socketpair(...):
        ...
    if not hasattr(socket, 'socketpair'):
        socket.socketpair = socketpair

-----

Both the pros and cons are tiny, so I'm genuinely curious which way you think is best, hence why I'm opening an issue to ask instead of just throwing a pull request your way.

Pro: Basic testing is a bit easier (but of marginal value because if someone is using this, primary testing needs to happen on a Windows runtime where the `hasattr` would pass anyway).

Con: Once `backports.socketpair.socketpair` is exposed, it's arguably part of the API/interface, and it's possible someone somewhere might, indeed, actually decide to use it, then complain if it ever gets hidden again.

-----

Personal example, in case you find it relevant:

In my `polyfill-callable` module, I only assign it to `builtins.callable` if `callable` doesn't already exist, but I expose `ctypes_callable` on the module if it can be defined. For me personally, it scratched the itch of "someone might want to invoke the polyfill/backport directly for some reason" and "maybe one day I'll have a different implementation of `callable` for some other Python runtime" (hence both exposing it if it's possible to use on the platform and naming the polyfill itself within the module with a prefix).

-----

P.S. Thanks for doing the good work of providing a backport like this. I really appreciated finding this and knowing I could just write code just using `socket.socketpair` without having to worry about it being usable/testable on Windows!

**Comment by mhils** [comment]
Hi,

If I'm not mistaken the current implementation is faster on systems where `socketpair` is available, but I really don't have a strong opinion on this. If anything, one could add it as `_socketpair` to discourage external use, but I think the current solution is just fine. Thanks.
